#### Logistic Regression's 
    J=0, dw1= 0, dw2=0, db=0
        for i in range(m):
            z = W.T*x[i]+b
            a = sigmoid (zi)
            j += -(y[i]log(a[i])+(1-y[i])log(1-a[i])) #loss function
            dz = a[i] - y[i]
            dw1 += x1[i]*dz[i]
            dw2 += x2[i]*dz[i]
            db  += dz[i]
        J = j/m, dw1 =dw1/m, dw2 = dw2/m 
        db= db/m

#### Vectorizing Logistic Regression's 
    
    Z = W.T*X+b
      = np.dot(W.T,X)+b
    A = Sig(A)
    dZ =A - Y
    dW = 1/m (X*dZ.T)
    db = 1/m np.sum(dZ)
    
Gradient descent:
    
    W := W - learningrate(dW)
    b := b - learningrate(db)
    
still need for loop to run each time Gradient descent.(but only)

In [1]:
import numpy as np

#### Broadcasting example 
    
    python will copy the matrix m or n times
    
    matrix (m,n)  +-*/ (1,n)  --> (m,n)
    matrix (m,n)  +-*/ (m,1)  --> (m,n)

In [3]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0) #vertical sum 
print(cal)

[ 59.  239.  155.4  76.9]


In [12]:
percentage = 100*(A/cal.reshape(1,4)).round(4)
print(percentage)

[[94.92  0.    2.83 88.43]
 [ 2.03 43.51 33.46 10.4 ]
 [ 3.05 56.49 63.71  1.17]]


#### A note on python/numpy vectors

In [16]:
a = np.random.randn(5) # not reconmend, rank 1 array
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T)) 

[ 0.47287441 -1.63163929 -0.32348058  0.08125577  1.39217616]
(5,)
[ 0.47287441 -1.63163929 -0.32348058  0.08125577  1.39217616]
4.935253615556018


In [17]:
a = np.random.randn(5,1) # 5 by 1 matrix!
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

[[ 1.11756731]
 [ 1.01311584]
 [ 0.87709781]
 [-1.03156429]
 [ 0.10268494]]
(5, 1)
[[ 1.11756731  1.01311584  0.87709781 -1.03156429  0.10268494]]
[[ 1.24895669  1.13222515  0.98021584 -1.15284253  0.11475733]
 [ 1.13222515  1.02640371  0.88860169 -1.04509413  0.10403174]
 [ 0.98021584  0.88860169  0.76930057 -0.90478278  0.09006473]
 [-1.15284253 -1.04509413 -0.90478278  1.06412489 -0.10592611]
 [ 0.11475733  0.10403174  0.09006473 -0.10592611  0.0105442 ]]
